server_ip: "141.85.232.73"
server_port: 9090
queue_size: 10
# topics must contain information:
# [topic_name, topic_type, optional: end_topic_name]
# if end_topic_name is not set same name will be used

remote_topics: [
  ["/remote_topic", ["std_msgs.msg", "String"]],
  ["/remote_topic2", ["std_msgs.msg", "String"]]
]

local_topics: [
  ["/local_topic",  ["std_msgs.msg", "String"], "/from_the_other_side"]
]